name: taxbrain-dev
channels:
- PSLmodels
- conda-forge
dependencies:
- python>=3.6.5
- taxcalc>=2.5.0
- behresp>=0.9.0
- pandas>=0.23
- numpy>=1.13
- pytest
- dask
- bokeh
- markdown
- cairo
- pango
- phantomjs
- tabulate
- weasyprint
- selenium
- pypandoc
- pip
- pip:
  - compdevkit
