name: taxbrain-dev
channels:
- PSLmodels
- conda-forge
dependencies:
- python>=3.6.5
- taxcalc>=2.0.0
- behresp>=0.7.0
- pandas>=0.23
- numpy>=1.13
- pytest
- dask
- paramtools
- marshmallow
- pip:
  - compdevkit
