package:
  name: taxbrain
  version: 0.0.0

requirements:
  build:
    - python
    - "taxcalc>1.0.0"
    - behresp
    - pandas
    - dask
    - numpy

run:
  - python
  - "taxcalc>1.0.0"
  - behresp
  - pandas
  - dask
  - numpy

test:
  imports:
    - taxbrain

about:
  home: https://github.com/PSLmodels/Tax-Brain