package:
  name: taxbrain
  version: 0.0.0

requirements:
  build:
    - python
    - "taxcalc>1.1.0"
    - "behresp>=0.7.0"
    - dask
    - paramtools
    - marshmallow

  run:
    - python
    - "taxcalc>1.1.0"
    - "behresp>=0.7.0"
    - dask
    - paramtools
    - marshmallow

about:
  home: https://github.com/PSLmodels/Tax-Brain