package:
  name: taxbrain
  version: 0.0.0

build:
  script: pip install weasyprint tabulate selenium
          conda install -c conda-forge phantomjs

requirements:
  build:
    - python
    - "taxcalc>=2.2.0"
    - "behresp>=0.8.0"
    - dask

  run:
    - python
    - "taxcalc>=2.2.0"
    - "behresp>=0.8.0"
    - dask
    - bokeh
    - markdown
    - cairo
    - pango

about:
  home: https://github.com/PSLmodels/Tax-Brain